<?xml version="1.0"?>
<robot name="phylax" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find phylax_description)/urdf/phylax.gazebo.xacro" />

<xacro:property name="deg_to_rad" value="0.017453"/>
<xacro:property name="PI" value="3.14"/>

<xacro:property name="chassis_len" value=".380"/>
<xacro:property name="chassis_width" value="0.165"/>
<xacro:property name="chassis_height" value="0.070"/>

<xacro:property name="wheel_radius" value="0.06"/>
<xacro:property name="wheel_width" value="0.06"/>
<xacro:property name="wheel_height" value="0.12"/>
<xacro:property name="wheel_mass" value=".480"/>

<xacro:macro name="cylinder_inertia" params ="m r h">
  <inertial>
   <mass value="${m}"/>
   <inertia ixx="${m*(3*r*r+h*h)/12}"  ixy="0.0" ixz="0.0"
            iyy="${m*(3*r*r+h*h)/12}"  iyz= "0.0"
            izz="${m*r*r/2}"/>
   </inertial>
</xacro:macro>

<xacro:macro name= "inertial_matrix" params="mass">
  <inertial>
    <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0" ixz="0.0"/>
   </inertial>
 </xacro:macro>

<xacro:macro name="Transmission_block" params="joint_name">
   <transmission name="${joint_name}_trans">
    <type>transmission_interface/SimpleTransmission</type>
     <joint name="${joint_name}">     
       <hardwareInterface>PositionJointInterface</hardwareInterface>
     </joint>
    <actuator name="${joint_name}_motor">
      <mechanicalReduction>1</mechanicalReduction>
     </actuator>
    </transmission>
 </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
          <box size="0.42 0.290 0.000001"/>
      </geometry>
      <material name="saffron">
          <color rgba="0.95 0.81 0.24 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.42 0.290 0.000001"/>
      </geometry>
    </collision>        
  </link>

<link name="chassis_link">
  <visual>
    <origin rpy="${PI/2} 0 0" xyz="0 0 -0.018"/>
    <geometry>
      <mesh filename="package://phylax_description/meshes/wild_thumper_6wd_chassis.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </visual>
  <collision>/><origin rpy="${PI/2} 0 0" xyz="0 0 -0.018"/>
    <geometry>
      <mesh filename="package://phylax_description/meshes/wild_thumper_6wd_chassis.stl" scale="0.001 0.001 0.001"/>
    </geometry>
  </collision>
  <xacro:inertial_matrix mass="2.5"/>
</link>
  <joint name="chassis_link_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint> 

  <link name="top_chassis">
      <visual>
          <origin rpy=" 0 0 0" xyz="-0.16 -0.008 -0.078"/>
          <geometry>
              <mesh filename="package://phylax_description/meshes/top_chassis.stl" scale="0.001 0.001 0.001"/>
          </geometry>
      </visual>
  </link>

  <joint name="top_chassis_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="top_chassis"/>
    <origin rpy="0 0 0" xyz="0.0 0.0 0.058"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>    

<xacro:macro name="wheel" params="pos side xyz xyzi cy">   
  <link name="${pos}_${side}_wheel">
    <visual>
      <origin xyz="${xyz}" rpy="${-PI/2} 0 0"/>
      <geometry>
        <mesh filename="package://phylax_description/meshes/${side}_wheel.stl" scale="0.001 0.001 0.001"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 ${cy} 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder radius="0.06" length="0.062"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
  </link>

  <gazebo reference="${pos}_${side}_wheel">
    <mu1 value="1.0"/>
    <mu2 value="1.0"/>
    <kp value="1000000.0" />
    <kd value="1.0" />
    <fdir1 value="1 0 0"/>
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="${pos}_${side}_wheel_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="${pos}_${side}_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="${xyzi}" rpy="0 0 0"/>
    <limit effort= "100" velocity="100"/>
    <dynamics damping="0.0" friction="0.0"/>     
  </joint>

  <transmission name="${pos}_${side}_wheel_trans" type="SimpleTransmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${pos}_${side}_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="{pos}_${side}_wheel_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</xacro:macro>

<xacro:wheel pos="front" side="left"  xyz="-0.023 -${chassis_width/2-0.01} 0.068" xyzi="0.150 ${chassis_width/2} 0" cy="0.036"/>
<xacro:wheel pos="front" side="right" xyz="-0.023 -${chassis_width-0.02} 0.068" xyzi="0.150 -${chassis_width/2} 0" cy="-0.036"/>
<xacro:wheel pos="center" side="left" xyz="-0.023 -${chassis_width/2-0.01} 0.068" xyzi="0 ${chassis_width/2} 0" cy="0.036"/>
<xacro:wheel pos="center" side="right" xyz="-0.023 -${chassis_width-0.02} 0.068" xyzi="0 -${chassis_width/2} 0" cy="-0.036"/>
<xacro:wheel pos="rear" side="left" xyz="-0.023 -${chassis_width/2-0.01} 0.068" xyzi="-0.150 ${chassis_width/2} 0" cy="0.036"/>
<xacro:wheel pos="rear" side="right" xyz="-0.023 -${chassis_width-0.02} 0.068" xyzi="-0.150 -${chassis_width/2} 0" cy="-0.036"/> 

 <xacro:include filename="$(find phylax_description)/urdf/accessories.urdf.xacro" />

</robot>
