#!/usr/bin/env python

import os
import robot_upstart

j = robot_upstart.Job(workspace_setup=os.environ['ROBOT_SETUP'])
j.add(package="phylax_base", filename="launch/phylax.launch")
j.add(package="jackal_bringup", filename="launch/phylax_lidar.launch")
j.install()