phylax_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

phylax_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  twist_covariance_diagonal: [0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
  cmd_vel_timeout: 0.0

  k_l: 0.0
  k_r: 0.0

  enable_odom_tf: false

  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.0   # rad/s^2
